package cn.kuzuanpa.ktfruaddon.tile.computerCluster.controller;

import cn.kuzuanpa.ktfruaddon.api.tile.GTTileEntityRegistry;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.IStringBaseStructure;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.StructureContext;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.mode.layer.LayerStructure;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.predicate.AirPredicate;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.predicate.PartPredicate;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.predicate.special.ComputePartPredicate;
import cn.kuzuanpa.ktfruaddon.api.tile.util.TileDesc;
import gregapi.tileentity.multiblocks.MultiTileEntityMultiBlockPart;

/**
 * A 33 x 33 x 33 phase-locked spacetime simulation array.  Every layer is
 * deliberately declared below: this is a construction layout, not a generated shape.
 */
public class SpacetimeComputeControllerT1 extends SpacetimeComputeController {
    private static final IStringBaseStructure STRUCTURE = new LayerStructure(StructureContext.Axis.Y).layerRule("AAABBBCCCDDDEFFFGGGHHHIIIJJJKKLLM")
            .fixedLayer('A',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "           FFFFFFFFFFF           ",
                    "                                 ",
                    "                                 ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "        F               F        ",
                    "                                 ",
                    "                                 ",
                    "           FFFFFFFFFFF           ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('B',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "        FFFFFFFFFFFFFFFFF        ",
                    "                                 ",
                    "                                 ",
                    "     F                     F     ",
                    "     F     PPPPPPPPPPP     F     ",
                    "     F                     F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F   P             P   F     ",
                    "     F                     F     ",
                    "     F     PPPPPPPPPPP     F     ",
                    "     F                     F     ",
                    "                                 ",
                    "                                 ",
                    "        FFFFFFFFFFFFFFFFF        ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('C',
                    "                                 ",
                    "                                 ",
                    "     FFFFFFFFFFFFFFFFFFFFFFF     ",
                    "                                 ",
                    "                                 ",
                    "  F                           F  ",
                    "  F                           F  ",
                    "  F      PPPPPPPPPPPPPPP      F  ",
                    "  F                           F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P   AAAAAAAAAAA   P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F                           F  ",
                    "  F      PPPPPPPPPPPPPPP      F  ",
                    "  F                           F  ",
                    "  F                           F  ",
                    "                                 ",
                    "                                 ",
                    "     FFFFFFFFFFFFFFFFFFFFFFF     ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('D',
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ",
                    "                                 ",
                    " F              E              F ",
                    " F     PPPPPPPPPPPPPPPPPPP     F ",
                    " F                             F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F  EP  L LAAAAAAAAAAAL L  PE  F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F                             F ",
                    " F     PPPPPPPPPPPPPPPPPPP     F ",
                    " F              E              F ",
                    "                                 ",
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ")
            .fixedLayer('E',
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ",
                    "                                 ",
                    " F              S              F ",
                    " F     PPPPPPPPPPPPPPPPPPP     F ",
                    " F                             F ",
                    " F   P                     P   F ",
                    " F   P  K       L       K  P   F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F  SP  L LAAAAAAAAAAAL L  PS  F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F   P  K       L       K  P   F ",
                    " F   P                     P   F ",
                    " F                             F ",
                    " F     PPPPPPPPPPPPPPPPPPP     F ",
                    " F              S              F ",
                    "                                 ",
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ")
            .fixedLayer('F',
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ",
                    "                                 ",
                    " F    PPPPPPPPPPPPPPPPPPPPP    F ",
                    " F                             F ",
                    " F  P                       P  F ",
                    " F  P                       P  F ",
                    " F  P           L           P  F ",
                    " F  P           C           P  F ",
                    " F  P           L           P  F ",
                    " F  P      CAAAAAAAAAC      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P   LCLAAAAAAAAAAALCL   P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      CAAAAAAAAAC      P  F ",
                    " F  P           L           P  F ",
                    " F  P           C           P  F ",
                    " F  P           L           P  F ",
                    " F  P                       P  F ",
                    " F  P                       P  F ",
                    " F                             F ",
                    " F    PPPPPPPPPPPPPPPPPPPPP    F ",
                    "                                 ",
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ")
            .fixedLayer('G',
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ",
                    "                                 ",
                    " F    PPPPPPPPPPPPPPPPPPPPP    F ",
                    " F                             F ",
                    " F  P                       P  F ",
                    " F  P                       P  F ",
                    " F  P           L           P  F ",
                    " F  P                       P  F ",
                    " F  P        C  L  C        P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P     CAAAAAAAAAAAC     P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P   L LAAAAAAAAAAAL L   P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P     CAAAAAAAAAAAC     P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P      AAAAAAAAAAA      P  F ",
                    " F  P        C  L  C        P  F ",
                    " F  P                       P  F ",
                    " F  P           L           P  F ",
                    " F  P                       P  F ",
                    " F  P                       P  F ",
                    " F                             F ",
                    " F    PPPPPPPPPPPPPPPPPPPPP    F ",
                    "                                 ",
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ")
            .fixedLayer('H',
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ",
                    "                                 ",
                    " F                             F ",
                    " F     PPPPPPPPPPPPPPPPPPP     F ",
                    " F              P              F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   PP L LAAAAAAAAAAAL L PP   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P     AAAAAAAAAAA     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F   P          L          P   F ",
                    " F   P                     P   F ",
                    " F              P              F ",
                    " F     PPPPPPPPPPPPPPPPPPP     F ",
                    " F                             F ",
                    "                                 ",
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ")
            .fixedLayer('I',
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ",
                    "                                 ",
                    " F                             F ",
                    " F                             F ",
                    " F      PPPPPPPPPPPPPPPPP      F ",
                    " F                             F ",
                    " F    P                   P    F ",
                    " F    P                   P    F ",
                    " F    P                   P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P    AAAAAAAAAAA    P    F ",
                    " F    P                   P    F ",
                    " F    P                   P    F ",
                    " F    P                   P    F ",
                    " F                             F ",
                    " F      PPPPPPPPPPPPPPPPP      F ",
                    " F                             F ",
                    " F                             F ",
                    "                                 ",
                    "                                 ",
                    "    FFFFFFFFFFFFFFFFFFFFFFFFF    ",
                    "                                 ")
            .fixedLayer('J',
                    "                                 ",
                    "                                 ",
                    "     FFFFFFFFFFFFFFFFFFFFFFF     ",
                    "                                 ",
                    "                                 ",
                    "  F                           F  ",
                    "  F                           F  ",
                    "  F      PPPPPPPPPPPPPPP      F  ",
                    "  F                           F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F    P                 P    F  ",
                    "  F                           F  ",
                    "  F      PPPPPPPPPPPPPPP      F  ",
                    "  F                           F  ",
                    "  F                           F  ",
                    "                                 ",
                    "                                 ",
                    "     FFFFFFFFFFFFFFFFFFFFFFF     ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('K',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "       FFFFFFFFFFFFFFFFFFF       ",
                    "                                 ",
                    "                                 ",
                    "    F                       F    ",
                    "    F                       F    ",
                    "    F      PPPPPPPPPPP      F    ",
                    "    F                       F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F    P             P    F    ",
                    "    F                       F    ",
                    "    F      PPPPPPPPPPP      F    ",
                    "    F                       F    ",
                    "    F                       F    ",
                    "                                 ",
                    "                                 ",
                    "       FFFFFFFFFFFFFFFFFFF       ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('L',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "          FFFFFFFFFFFFF          ",
                    "                                 ",
                    "                                 ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "       F                 F       ",
                    "                                 ",
                    "                                 ",
                    "          FFFFFFFFFFFFF          ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('M',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "             FFFFFFF             ",
                    "                                 ",
                    "                                 ",
                    "          F           F          ",
                    "          F           F          ",
                    "          F           F          ",
                    "          F           F          ",
                    "          F           F          ",
                    "          F           F          ",
                    "          F           F          ",
                    "                                 ",
                    "                                 ",
                    "             FFFFFFF             ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .where('F', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31080, MultiTileEntityMultiBlockPart.ONLY_ENERGY)))
            .where('P', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31081)))
            .where('L', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31082)))
            .where('C', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31083)))
            .where('S', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31084)))
            .where('E', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31080, MultiTileEntityMultiBlockPart.ONLY_ENERGY_IN)))
            .where('K', new ComputePartPredicate())
            .where('A', new AirPredicate())
            .setOffset(-16, 0, 0);

    public SpacetimeComputeControllerT1() { super(2097152L, 2000L, 4); }
    @Override public IStringBaseStructure getStructure() { return STRUCTURE; }
    @Override public String getTileEntityName() { return "ktfru.multitileentity.compute.spacetime.t1"; }
}
