package cn.kuzuanpa.ktfruaddon.tile.computerCluster.controller;

import cn.kuzuanpa.ktfruaddon.api.tile.GTTileEntityRegistry;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.IStringBaseStructure;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.StructureContext;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.mode.layer.LayerStructure;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.predicate.AirPredicate;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.predicate.PartPredicate;
import cn.kuzuanpa.ktfruaddon.api.tile.structure.stringBased.predicate.special.ComputePartPredicate;
import cn.kuzuanpa.ktfruaddon.api.tile.util.TileDesc;
import gregapi.tileentity.multiblocks.MultiTileEntityMultiBlockPart;

/**
 * A 33 x 65 x 33 zero-point causality observatory.  The literal fixed layers
 * keep the structure extensible: dedicated hooks can be added to exact decks.
 */
public class SpacetimeComputeControllerT2 extends SpacetimeComputeController {
    private static final IStringBaseStructure STRUCTURE = new LayerStructure(StructureContext.Axis.Y).layerRule("AAAABBBBBCCCCCDDDDDEEEEFGGGGHHHHIJJJJKLLLLLMMMMMNNNNNOOOOOPPPPPQQ")
            .fixedLayer('A',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "             HHHHHHH             ",
                    "                                 ",
                    "                                 ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "                                 ",
                    "                                 ",
                    "             HHHHHHH             ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('B',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "          HHHHHHHHHHHHH          ",
                    "                                 ",
                    "                                 ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "                                 ",
                    "                                 ",
                    "          HHHHHHHHHHHHH          ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('C',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "       HHHHHHHHHHHHHHHHHHH       ",
                    "                                 ",
                    "                                 ",
                    "    H                       H    ",
                    "    H                       H    ",
                    "    H      RRRRRRRRRRR      H    ",
                    "    H                       H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H                       H    ",
                    "    H      RRRRRRRRRRR      H    ",
                    "    H                       H    ",
                    "    H                       H    ",
                    "                                 ",
                    "                                 ",
                    "       HHHHHHHHHHHHHHHHHHH       ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('D',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "                                 ",
                    " H              E              H ",
                    " H                             H ",
                    " H      RRRRRRRRRRRRRRRRR      H ",
                    " H                             H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " HG E R                   R E  H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H    R                   R    H ",
                    " H                             H ",
                    " H      RRRRRRRRRRRRRRRRR      H ",
                    " H                             H ",
                    " H              E              H ",
                    "                                 ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('E',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "                O                ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    " H                             H ",
                    " H  R           E           R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R     L           L     R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H OR E L  AAAAAAAAAAA  L E RO H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R     L           L     R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R           E           R  H ",
                    " H                             H ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    "                O                ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('F',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "                                 ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    " H                             H ",
                    " H  R                       R  H ",
                    " H  R  K                 K  R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R     L           L     R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AZAAAAAAAZA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R   L  AAAAAAAAAAA  L   R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AZAAAAAAAZA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R     L           L     R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R  K                 K  R  H ",
                    " H  R                       R  H ",
                    " H                             H ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    "                                 ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('G',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "     RRRRRRRRRRRRRRRRRRRRRRR     ",
                    " H        R           R        H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H R            L            R H ",
                    " H R                         R H ",
                    " H R      L           L      R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R    L  AAAAAAAAAAA  L    R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R      L           L      R H ",
                    " H R                         R H ",
                    " H R            L            R H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H        R           R        H ",
                    "     RRRRRRRRRRRRRRRRRRRRRRR     ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('H',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "     RRRRRRRRRRRRRRRRRRRRRRR     ",
                    " H                             H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H R            L            R H ",
                    " H R                         R H ",
                    " H R      L           L      R H ",
                    " H R       AAZAAAAAZAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R    L  AAAAAAAAAAA  L    R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAZAAAAAZAA       R H ",
                    " H R      L           L      R H ",
                    " H R                         R H ",
                    " H R            L            R H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H R                         R H ",
                    " H                             H ",
                    "     RRRRRRRRRRRRRRRRRRRRRRR     ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('I',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "     RRRRRRRRRRRRRRRRRRRRRRR     ",
                    " H                             H ",
                    " H R                         R H ",
                    " H R        K       K        R H ",
                    " H R                         R H ",
                    " H R            L            R H ",
                    " H R                         R H ",
                    " H R      L           L      R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       ZAAAAAAAAAZ       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R    L  AAAAAAAAAAA  L    R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       ZAAAAAAAAAZ       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R       AAAAAAAAAAA       R H ",
                    " H R      L           L      R H ",
                    " H R                         R H ",
                    " H R            L            R H ",
                    " H R                         R H ",
                    " H R        K       K        R H ",
                    " H R                         R H ",
                    " H                             H ",
                    "     RRRRRRRRRRRRRRRRRRRRRRR     ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('J',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "                                 ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    " H                             H ",
                    " H  R                       R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R     L           L     R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R   L  AAAAAAAAAAA  L   R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R     L           L     R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R                       R  H ",
                    " H                             H ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    "                                 ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('K',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "                                 ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    " H                             H ",
                    " H  R                       R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R     L     Z     L     R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R K    AAAAAAAAAAA    K R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R   L ZAAAAAAAAAAAZ L   R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R K    AAAAAAAAAAA    K R  H ",
                    " H  R      AAAAAAAAAAA      R  H ",
                    " H  R     L     Z     L     R  H ",
                    " H  R                       R  H ",
                    " H  R           L           R  H ",
                    " H  R                       R  H ",
                    " H  R                       R  H ",
                    " H                             H ",
                    " H    RRRRRRRRRRRRRRRRRRRRR    H ",
                    "                                 ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('L',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                G                ",
                    "                                 ",
                    " H                             H ",
                    " H     RRRRRRRRRRRRRRRRRRR     H ",
                    " H                             H ",
                    " H   R                     R   H ",
                    " H   R          L          R   H ",
                    " H   R                     R   H ",
                    " H   R    L           L    R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " HG  R  L  AAAAAAAAAAA  L  R  GH ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R     AAAAAAAAAAA     R   H ",
                    " H   R    L           L    R   H ",
                    " H   R                     R   H ",
                    " H   R          L          R   H ",
                    " H   R                     R   H ",
                    " H                             H ",
                    " H     RRRRRRRRRRRRRRRRRRR     H ",
                    " H                             H ",
                    "                                 ",
                    "                G                ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('M',
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ",
                    "                                 ",
                    " H                             H ",
                    " H                             H ",
                    " H      RRRRRRRRRRRRRRRRR      H ",
                    " H                             H ",
                    " H    R         L         R    H ",
                    " H    R                   R    H ",
                    " H    R   L           L   R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R L  AAAAAAAAAAA  L R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R    AAAAAAAAAAA    R    H ",
                    " H    R   L           L   R    H ",
                    " H    R                   R    H ",
                    " H    R         L         R    H ",
                    " H                             H ",
                    " H      RRRRRRRRRRRRRRRRR      H ",
                    " H                             H ",
                    " H                             H ",
                    "                                 ",
                    "                                 ",
                    "    HHHHHHHHHHHHHHHHHHHHHHHHH    ",
                    "                                 ")
            .fixedLayer('N',
                    "                                 ",
                    "                                 ",
                    "     HHHHHHHHHHHHHHHHHHHHHHH     ",
                    "                                 ",
                    "                                 ",
                    "  H                           H  ",
                    "  H                           H  ",
                    "  H      RRRRRRRRRRRRRRR      H  ",
                    "  H                           H  ",
                    "  H    R                 R    H  ",
                    "  H    R                 R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R   AAAAAAAAAAA   R    H  ",
                    "  H    R                 R    H  ",
                    "  H    R                 R    H  ",
                    "  H                           H  ",
                    "  H      RRRRRRRRRRRRRRR      H  ",
                    "  H                           H  ",
                    "  H                           H  ",
                    "                                 ",
                    "                                 ",
                    "     HHHHHHHHHHHHHHHHHHHHHHH     ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('O',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "       HHHHHHHHHHHHHHHHHHH       ",
                    "                                 ",
                    "                                 ",
                    "    H                       H    ",
                    "    H                       H    ",
                    "    H      RRRRRRRRRRR      H    ",
                    "    H                       H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H    R             R    H    ",
                    "    H                       H    ",
                    "    H      RRRRRRRRRRR      H    ",
                    "    H                       H    ",
                    "    H                       H    ",
                    "                                 ",
                    "                                 ",
                    "       HHHHHHHHHHHHHHHHHHH       ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('P',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "          HHHHHHHHHHHHH          ",
                    "                                 ",
                    "                                 ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "       H                 H       ",
                    "                                 ",
                    "                                 ",
                    "          HHHHHHHHHHHHH          ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .fixedLayer('Q',
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "             HHHHHHH             ",
                    "                                 ",
                    "                                 ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "          H           H          ",
                    "                                 ",
                    "                                 ",
                    "             HHHHHHH             ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ",
                    "                                 ")
            .where('H', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31085, MultiTileEntityMultiBlockPart.ONLY_ENERGY)))
            .where('R', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31086)))
            .where('Z', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31087)))
            .where('G', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31088)))
            .where('O', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31089)))
            .where('L', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31090)))
            .where('E', new PartPredicate(new TileDesc(GTTileEntityRegistry.ktfruaddon, 31085, MultiTileEntityMultiBlockPart.ONLY_ENERGY_IN)))
            .where('K', new ComputePartPredicate())
            .where('A', new AirPredicate())
            .setOffset(-16, 0, 0);

    public SpacetimeComputeControllerT2() { super(67108864L, 200000L, 12); }
    @Override public IStringBaseStructure getStructure() { return STRUCTURE; }
    @Override public String getTileEntityName() { return "ktfru.multitileentity.compute.spacetime.t2"; }
}
